name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: MovieCatalogExam.slnx
      Test_Project_Path: MovieCatalogExam/MovieCatalogExam.csproj
      Wap_Project_Directory: MovieCatalogExam.Package
      Wap_Project_Path: MovieCatalogExam.Package/MovieCatalogExam.Package.wapproj

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - uses: microsoft/setup-msbuild@v2

    - run: dotnet test

    - run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
